#pragma once

// Generated by cricket for robot "{{name}}" (language: cuda). Do not edit.
//
// Straight-line, robot-specialized kinematics for CUDA kernels. Every function is per-thread and
// allocation-free, so it can be called from any solver loop (thread-, warp- or block-tiered).
//
//   q        (n_q)            joint positions, ordered as `joint_names`
//   pose     (7)              [qw, qx, qy, qz, tx, ty, tz], world frame
//   jacobian (6 * n_q)        row-major, rows (vx, vy, vz, wx, wy, wz), LOCAL_WORLD_ALIGNED at the EE origin
//   spheres  (4 * n_spheres)  [x, y, z, r] per collision sphere, world frame
//   poses    (7 * n_frames)   frame_poses(): world pose of each frame named in the "trace_frames" data key
//   qdd      (n_q)            forward_dynamics() (when generated with forward dynamics): accelerations
//                             from [q, qd, tau] (3 * n_q), gravity -9.81 along world z
//   tau      (n_q)            inverse_dynamics(): torques from [q, qd, qdd] (3 * n_q)
//   M        (n_q * n_q)      mass_matrix(): full symmetric joint-space inertia, column-major
//   dtau     (2 * n_q * n_q)  inverse_dynamics_derivatives(): [dtau/dq, dtau/dqd] from [q, qd, qdd], column-major
//
// Define CRICKET_HD before including to override the function qualifiers.

#ifndef __CUDACC_RTC__  // NVRTC provides the math functions as builtins
#include <math.h>
#endif

#ifndef CRICKET_HD
#ifdef __CUDACC__
#define CRICKET_HD __host__ __device__ __forceinline__
#else
#define CRICKET_HD inline
#endif
#endif

// NOLINTBEGIN(*-magic-numbers)
namespace cricket::robots::{{lower(name)}}
{
    constexpr int n_q = {{n_q}};
    constexpr int n_spheres = {{n_spheres}};
    constexpr const char *end_effector = "{{end_effector}}";
    constexpr const char *joint_names[n_q] = {"{{join(joint_names, "\", \"")}}"};

    namespace detail
    {
        // y = [t (3), R column-major (9)] -> pose = [qw, qx, qy, qz, tx, ty, tz]
        CRICKET_HD void pack_pose(const float *y, float *pose)
        {
            const float r00 = y[3], r10 = y[4], r20 = y[5];
            const float r01 = y[6], r11 = y[7], r21 = y[8];
            const float r02 = y[9], r12 = y[10], r22 = y[11];

            const float trace = r00 + r11 + r22;
            if (trace > 0.f)
            {
                const float s = 0.5f / sqrtf(trace + 1.f);
                pose[0] = 0.25f / s;
                pose[1] = (r21 - r12) * s;
                pose[2] = (r02 - r20) * s;
                pose[3] = (r10 - r01) * s;
            }
            else if (r00 > r11 and r00 > r22)
            {
                const float s = 2.f * sqrtf(1.f + r00 - r11 - r22);
                pose[0] = (r21 - r12) / s;
                pose[1] = 0.25f * s;
                pose[2] = (r01 + r10) / s;
                pose[3] = (r02 + r20) / s;
            }
            else if (r11 > r22)
            {
                const float s = 2.f * sqrtf(1.f + r11 - r00 - r22);
                pose[0] = (r02 - r20) / s;
                pose[1] = (r01 + r10) / s;
                pose[2] = 0.25f * s;
                pose[3] = (r12 + r21) / s;
            }
            else
            {
                const float s = 2.f * sqrtf(1.f + r22 - r00 - r11);
                pose[0] = (r10 - r01) / s;
                pose[1] = (r02 + r20) / s;
                pose[2] = (r12 + r21) / s;
                pose[3] = 0.25f * s;
            }

            pose[4] = y[0];
            pose[5] = y[1];
            pose[6] = y[2];
        }
    }  // namespace detail

    CRICKET_HD void ee_pose(const float *x, float *pose)
    {
        {% if eefk_code_vars > 0 %}float v[{{eefk_code_vars}}];{% endif %}
        float y[{{eefk_code_output}}];

        {{eefk_code}}

        detail::pack_pose(y, pose);
    }

    CRICKET_HD void ee_pose_jacobian(const float *x, float *pose, float *jacobian)
    {
        {% if eejac_code_vars > 0 %}float v[{{eejac_code_vars}}];{% endif %}
        float y[{{eejac_code_output}}];

        {{eejac_code}}

        detail::pack_pose(y, pose);
        for (int i = 0; i < 6 * n_q; ++i)
        {
            jacobian[i] = y[12 + i];
        }
    }

    CRICKET_HD void sphere_centers(const float *x, float *spheres)
    {
        {% if spherefk_code_vars > 0 %}float v[{{spherefk_code_vars}}];{% endif %}
        float *y = spheres;

        {{spherefk_code}}
    }
{% if exists("framesfk_code") %}
    constexpr int n_frames = {{length(trace_frames)}};
    constexpr const char *frame_names[n_frames] = {"{{join(trace_frames, "\", \"")}}"};

    // World pose of every frame in `frame_names`, 7 floats each, in that order.
    CRICKET_HD void frame_poses(const float *x, float *poses)
    {
        {% if framesfk_code_vars > 0 %}float v[{{framesfk_code_vars}}];{% endif %}
        float y[{{framesfk_code_output}}];

        {{framesfk_code}}

        for (int i = 0; i < n_frames; ++i)
        {
            detail::pack_pose(y + 12 * i, poses + 7 * i);
        }
    }
{% endif %}{% if exists("forward_dynamics_code") %}
    // Forward dynamics (ABA) of the dynamics model: x = [q, qd, tau], each n_q long.
    CRICKET_HD void forward_dynamics(const float *x, float *qdd)
    {
        {% if forward_dynamics_code_vars > 0 %}float v[{{forward_dynamics_code_vars}}];{% endif %}
        float *y = qdd;

        {{forward_dynamics_code}}
    }
{% endif %}{% if exists("inverse_dynamics_code") %}
    // Inverse dynamics (RNEA) of the dynamics model: x = [q, qd, qdd], each n_q long.
    CRICKET_HD void inverse_dynamics(const float *x, float *tau)
    {
        {% if inverse_dynamics_code_vars > 0 %}float v[{{inverse_dynamics_code_vars}}];{% endif %}
        float *y = tau;

        {{inverse_dynamics_code}}
    }
{% endif %}{% if exists("mass_matrix_code") %}
    // Joint-space mass matrix (CRBA) of the dynamics model, n_q x n_q column-major.
    CRICKET_HD void mass_matrix(const float *x, float *M)
    {
        {% if mass_matrix_code_vars > 0 %}float v[{{mass_matrix_code_vars}}];{% endif %}
        float *y = M;

        {{mass_matrix_code}}
    }
{% endif %}{% if exists("inverse_dynamics_derivatives_code") %}
    // Inverse-dynamics derivatives: x = [q, qd, qdd] -> [dtau/dq, dtau/dqd], each n_q x n_q column-major.
    CRICKET_HD void inverse_dynamics_derivatives(const float *x, float *dtau)
    {
        {% if inverse_dynamics_derivatives_code_vars > 0 %}float v[{{inverse_dynamics_derivatives_code_vars}}];{% endif %}
        float *y = dtau;

        {{inverse_dynamics_derivatives_code}}
    }
{% endif %}
}  // namespace cricket::robots::{{lower(name)}}
// NOLINTEND(*-magic-numbers)
